api:
  image: miniwaveme/golang
  working_dir: /go/src/miniwave.me/api
  command: go run main.go
  volumes:
    - ./src:/go/src/miniwave.me/api
  links:
    - database
  environment:
    - DB_NAME=miniwaveme_api
database:
  image: mongo:3.0
  command: mongod --smallfiles --quiet --logpath=/dev/null
  volumes:
    - ./data/db:/data/db
