api:
  image: miniwaveme/golang
  working_dir: /go/src/miniwave.me/api/src
  command: go run main.go
  volumes:
    - ./src:/go/src/miniwave.me/api/src
    - ./log:/go/src/miniwave.me/api/log
    - ./cache:/go/src/miniwave.me/api/cache
    - ./config:/go/src/miniwave.me/api/config

  links:
    - database
    - redis
    - elasticsearch
  environment:
    - DB_NAME=miniwaveme_api
    - API_PORT=7512
  ports:
    - "7512:7512"

database:
  image: mongo:3.0
  command: mongod --smallfiles --quiet --logpath=/dev/null
  volumes:
    - ./data/db:/data/db
redis:
  image: redis:3.0
  command: redis-server --appendonly yes
  volumes:
    - ./data/redis:/data

elasticsearch:
  image: tutum/elasticsearch
  ports:
    - "9200:9200"
  environment:
    ELASTICSEARCH_USER: admin
    ELASTICSEARCH_PASS: password

#elk:
#  image: willdurand/elk
#  ports:
#    - "7050:80"
#  volumes:
#    - ./config/logstash:/etc/logstash
#  volumes_from:
#    - dataelk
#
#dataelk:
#  image: busybox
#  volumes:
#    - /data
#    - ./data/elk:/data/elk/data